%% Import data from spreadsheet
% Auto-generated by MATLAB on 2017/11/09 09:42:26

%% Import the data
[~, ~, raw] = xlsread('C:\Users\Toby\Documents\Tobys_Stuff\MATLAB\Natural_Frequencies\NaturalFrequencies_FieldData_full.xlsx','FieldData','B2:S767');

raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
stringVectors = string(raw(:,[1,2,7,9,10,11,12,13,15]));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[3,4,5,6,8,14,16,17,18]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Type = stringVectors(:,1);
Species = stringVectors(:,2);
fo = data(:,1);
DBH = data(:,2);
Height = data(:,3);
DBH1 = data(:,4);
Specieslong = categorical(stringVectors(:,3));
DBHH = data(:,5);
Authors = categorical(stringVectors(:,4));
forest = categorical(stringVectors(:,5));
VarName = stringVectors(:,6);
Location = stringVectors(:,7);
Author = categorical(stringVectors(:,8));
h = data(:,6);
Specieslong = stringVectors(:,9);
ENmm2Stuttgart1 = data(:,7);
rho = data(:,8);
E = data(:,9);
beam=DBH./(100.*Height.^2);

FD=table(Location, DBH, Height, fo,beam, 'VariableNames',{'Location','DBH','Height','fo','beam'});
clearvars -except FD