%% Import data from spreadsheet
% Auto-generated by MATLAB on 2018/08/27 14:54:05

%% Import the data
[~, ~, raw] = xlsread('C:\Users\Toby\Documents\Tobys_Stuff\MATLAB\Natural_Frequencies\NaturalFrequencies_ModelData.xlsx','ModelData','A2:AC1085');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
stringVectors = string(raw(:,[1,3,12,13,16]));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[2,4,5,6,7,8,9,10,11,14,15,17,18,19,20,21,22,23,24,25,26,27,28,29]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
MD = table;

%% Allocate imported array to column variable names
MD.Location = (stringVectors(:,1));
MD.index = data(:,1);
MD.Simnames = stringVectors(:,2);
MD.fo = data(:,2);
MD.fmax = data(:,3);
MD.dom = data(:,4);
MD.Nmodes = data(:,5);
MD.fo1 = data(:,6);
MD.fmax1 = data(:,7);
MD.dom1 = data(:,8);
MD.Nmodes1 = data(:,9);
MD.Simnames1 = stringVectors(:,3);
MD.VarName13 = stringVectors(:,4);
MD.imageoforder = data(:,10);
MD.ordermatching = data(:,11);
MD.ArchNames = stringVectors(:,5);
MD.TreeHeight = data(:,12);
MD.DBH = data(:,13);
MD.Beam=MD.DBH./(MD.TreeHeight.^2);
MD.TotalVolume = data(:,14);
MD.PathFraction = data(:,15);
MD.CrownHeight = data(:,16);
MD.MaxCrownWidth = data(:,17);
MD.AspectRatio=MD.MaxCrownWidth./MD.CrownHeight;
MD.CrownArea = data(:,18);
MD.CrownAsym = data(:,19);
MD.BranchingAngle = data(:,20);
MD.TotalSailArea = data(:,21);
MD.CVR = data(:,22);
MD.CoV_height = data(:,23);
MD.CoV=MD.CoV_height./MD.TreeHeight;
MD.num_cyls = data(:,24);

%% Clear temporary variables
clearvars data raw stringVectors R;